Repository nextcloud/maps, pull requests merged in 2019-08, with the labels that each got.

#75 Fix "endswith" declaration and remove contact groups colors
  js/contactsController.js
  lib/Controller/DevicesController.php
  lib/Controller/FavoritesController.php
  lib/Service/DevicesService.php
  lib/Service/FavoritesService.php
Labels: bug

#76 Update readme, info.xml, add screenshots
  README.md
  appinfo/info.xml
  screenshots/old-contacts.png
  screenshots/old-start.png
  screenshots/screenshot1.png
  screenshots/screenshot2.png
  screenshots/screenshot3.png
Labels: design, enhancement

#78 fix file hooks
  appinfo/app.php
  appinfo/application.php
  appinfo/info.xml
  lib/Hooks/FileHooks.php
Labels: bug

#80 Mention bias of Mercator map projection, thanks @alicetragedy
  README.md
  templates/settings/index.php
Labels: enhancement

#81 avoid showing sidebar when grabing the map to the right
  js/script.js
Labels: bug, design

#82 Fix search box position on mobile with navigation menu, ref #56
  css/style.scss
Labels: bug, design

#79 run photo and track scan on app installation
  appinfo/info.xml
  js/script.js
  lib/BackgroundJob/LaunchUsersInstallScanJob.php
  lib/BackgroundJob/UserInstallScanJob.php
  lib/Migration/InstallScan.php
Labels: enhancement, feature: :mountain_biking_woman: tracks, feature: 🖼 photos

#87 refs #85 fix bug with unnamed contacts
  lib/Controller/ContactsController.php
Labels: bug, feature: 👥 contacts

#100 fix problem with chrome based mobile browsers because of win…
  js/script.js
Labels: bug, feature: 🗺 map

#98 attempt to fix bad inserted values for photo lat/lng
  lib/Service/PhotofilesService.php
Labels: bug, feature: 🖼 photos

#103 Added different mapbox profiles
  js/script.js
Labels: enhancement, feature: ↗️ routing
