Repository nextcloud/maps, pull requests merged in 2019-10, with the labels that each got.

#154 refs #132 fix popup shift when avatar appears late
  css/style.scss
Labels: bug, design, feature: 👥 contacts

#191 Fix issue165 routing engine titles are not translatable
  js/script.js
Labels: bug, feature: ↗️ routing

#189 Save current route
  css/style.scss
  js/script.js
Labels: enhancement, feature: ↗️ routing

#190 Fix issue166 OSRM demo mistakes
  js/script.js
Labels: bug, feature: ↗️ routing

#187 add Mapbox vector tiles support, not with self hosted servers FTM
  js/script.js
  lib/Controller/PageController.php
  package.json
  templates/content/index.php
Labels: enhancement, feature: 🗺 map

#188 Popups and tooltips fixes
  css/style.scss
  js/contactsController.js
  js/favoritesController.js
Labels: bug, enhancement, feature: :star: favorites, feature: 👥 contacts

#194 Update max-version to 18
  appinfo/info.xml
Labels: enhancement

#196 fix bug in names making dark and topographic inaccessible
  js/script.js
Labels: bug, feature: 🗺 map

#199 Fix device API null point values
  .gitlab-ci.yml
  lib/Service/DevicesService.php
  tests/Unit/Controller/DevicesControllerTest.php
Labels: bug, feature: 📱 devices
