Repository nextcloud/maps, pull requests merged in 2020-02, with the labels that each got.

#285 Fix typo
  lib/Service/PhotofilesService.php
Labels: bug

#292 Use Webpack
  .github/workflows/node.yml
  .gitignore
  Makefile
  babel.config.js
  composer.lock
  css/fontawesome/css/all.min.css
  css/fontawesome/css/brands.min.css
  css/fontawesome/css/fontawesome.min.css
  css/fontawesome/css/regular.min.css
  css/fontawesome/css/solid.min.css
  css/fontawesome/css/svg-with-js.min.css
  css/fontawesome/css/v4-shims.min.css
  css/fontawesome/webfonts/fa-brands-400.eot
  css/fontawesome/webfonts/fa-brands-400.ttf
  css/fontawesome/webfonts/fa-brands-400.woff
  css/fontawesome/webfonts/fa-brands-400.woff2
  css/fontawesome/webfonts/fa-regular-400.eot
  css/fontawesome/webfonts/fa-regular-400.ttf
  css/fontawesome/webfonts/fa-regular-400.woff
  css/fontawesome/webfonts/fa-regular-400.woff2
  css/fontawesome/webfonts/fa-solid-900.eot
  css/fontawesome/webfonts/fa-solid-900.ttf
  css/fontawesome/webfonts/fa-solid-900.woff
  css/fontawesome/webfonts/fa-solid-900.woff2
  js/external/lrm-graphhopper-1.2.0.min.js
  package-lock.json
  package.json
  src/adminSettings.js
  src/contactsController.js
  src/devicesController.js
  src/favoritesController.js
  src/filetypes.js
  src/nonLocalizedPhotosController.js
  src/photosController.js
  src/script.js
  src/tracksController.js
  src/utils.js
  templates/content/index.php
  templates/index.php
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: bug, technical debt

#281 Fixed time filter for photos.
  src/photosController.js
  src/script.js
Labels: bug

#299 Use global jQuery for now
  package-lock.json
  package.json
  src/adminSettings.js
  src/contactsController.js
  src/devicesController.js
  src/favoritesController.js
  src/filetypes.js
  src/nonLocalizedPhotosController.js
  src/photosController.js
  src/script.js
  src/tracksController.js
Labels: bug

#253 Create FUNDING.yml
  .github/FUNDING.yml
Labels: enhancement

#306 fix missing var in favoritesController
  src/favoritesController.js
Labels: bug, feature: :star: favorites

#309 fix another missing var in tracksController.js
  src/tracksController.js
Labels: bug, feature: :mountain_biking_woman: tracks

#314 Do not autoupdate composer dependencies
  Makefile
Labels: enhancement
